server.port=8080

shareit-server.url=http://localhost:9090

# RestTemplate configuration
rest.client.connection-timeout=5000
rest.client.read-timeout=10000
rest.client.max-connections=50
rest.client.max-per-route=20